name: Assign Reviewers
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-reviewers:
    if: github.event.pull_request.draft == false
    name: Add Reviewers
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: "${{ secrets.PLEDGE }}"
          configuration-path: '.github/workflows/config/reviewers.yml'
